services:
  node:
    build:
      context: .
    ports:
      - 8080
    volumes:
      - data:./data
volumes:
  data:
    driver_opts:
      size: 0.5Gi
endpoints:
  - path: /
    service: node
    port: 8080
