services:
  node:
    build:
      context: .
    ports:
      - 8080
    environment:
      - TG_TOKEN=$TG_TOKEN
      - CHAT_ID=$CHAT_ID
    volumes:
      - ./data
endpoints:
  - path: /
    service: node
    port: 8080
